export enum ResponseStatus {
  USER_ALREADY_EXISTS = 40001,
  USER_ALREADY_OR_PASSWORD_ERROR = 40002,
  MISSING_ARTICLE_TITLE = 41001,
  ARTICLE_ALREADY_EXISTS = 41002,
  ARTICLE_DOES_NOT_EXIST = 41003,
  SMS_SEND_FAIL = 41004,
  SMS_SEND_WAIT = 41005,
  PLEASE_SEND_THE_VERIFICATION_CODE_FIRST = 41006,
  VERIFICATION_CODE_ERROR = 41007,
}

export enum ResponseMessage {
  USER_ALREADY_EXISTS = '用户已存在',
  USER_ALREADY_OR_PASSWORD_ERROR = '用户不存在或密码错误',
  MISSING_ARTICLE_TITLE = '缺少文章标题',
  ARTICLE_ALREADY_EXISTS = '文章已存在',
  ARTICLE_DOES_NOT_EXIST = '文章不存在',
  SMS_SEND_FAIL = '短信发送失败',
  SMS_SEND_WAIT = '发送频率过快，轻稍后再发送',
  PLEASE_SEND_THE_VERIFICATION_CODE_FIRST = '请先发送验证码',
  VERIFICATION_CODE_ERROR = '验证码错误',
}
