kind: pipeline
type: docker
name: build

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - 172.17.0.1
      username: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      script:
        - cd /www/wwwroot/book_service
        - npm install
        - npm run build
        - pm2 restart all