kind: pipeline
type: docker
name: build

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: server_host
      user:
        from_secret: server_username
      password:
        from_secret: server_password
      port: 22
      command_timeout: 2m
      script:
        - cd /www/wwwroot/book_service
        - npm install
        - npm run build
        - pm2 restart all